targets:
  $default:
    builders:
      simple_code_gen|source_gen_part:
        enabled: true

builders:
  simple_code_gen:
      target: ":simple_code_gen"
      import: "package:simple_code_gen/builder.dart"
      builder_factories: ["simpleCodeGenerator"]
      build_extensions: {".dart":[".simple_extension.dart"]}
      auto_apply: dependents
      build_to: cache
      applies_builders: ["source_gen|combining_builder"]